version: '3.8'
services: 
    api:
        build: 
            dockerfile: Dockerfile
            context: server
        ports: 
            - "8081:8080"
        networks: 
            - backend
    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./kb-client
        expose: 
            - 4200
        ports: 
            - "4200:4200"
            - "49153:49153"
        volumes: 
            - /app/node_modules
            - ./kb-client:/app
        networks: 
            - backend
networks: 
    backend:
        driver: bridge
        