version: '3.8'
services: 
    postgres:
        image: 'postgres:latest'
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_USER: kbuser
            POSTGRES_PASSWORD: kbpwd
        volumes:
            - pgdata:/var/lib/postgresql/data
    api:
        image: "swarsa/kb-api"
        build: 
            dockerfile: Dockerfile
            context: server
        ports: 
            - "8081:8080"
    client:
        image: "swarsa/kb-client"
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./kb-client
        expose: 
            - 4200
        ports: 
            - "4200:4200"
            - "49153:49153"
        volumes:
            - /app/node_modules
            - ./kb-client:/app
volumes:
    pgdata: 
        external: true